### PR TITLE
Improve documentation and add charts

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Charts used in the Scottish budget analysis- e.g. the earnings variation chart.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
could you add an issue? who'd you like to review this?

**Comment by nikhilwoodruff** [comment]
@mikesmit this incorporates your branch (fixed merge conflicts), and also adds a fair amount of documentation.

The docs now have a page on:

* The `Simulation` class (via sphinx autodoc)
image

* Every leaf endpoint that you can pass into `Simulation.calculate`. Claude assisted with this but it was more of a joint process.

image

image

**Comment by nikhilwoodruff** [comment]
I'd like to merge if possible so as to move the repo away from its broken state- feedback still absolutely welcome!

**Comment by nikhilwoodruff** [comment]
Superseded by #62

**Pull request closed without merging**
